[pytest]
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"').

filterwarnings =
    ignore::StarletteDeprecationWarning
    ignore::DeprecationWarning:fastapi.applications